name: diffex
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- conda-forge::lpips 
- conda-forge::matplotlib 
- conda-forge::numpy<2
- conda-forge::pillow 
- conda-forge::pytorch-lightning==1.4.5
- conda-forge::torchmetrics==0.5.0
- conda-forge::scikit-learn 
- pytorch::pytorch 
- pytorch::torchvision 
- conda-forge::tqdm 
- conda-forge::wandb
- pip
- pip:
  - pytorch-fid
